# Generated by Django 4.0.6 on 2023-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='comment_reply', to='posts.commentpost'),
        ),
    ]
