# Generated by Django 4.0.6 on 2023-03-14 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_commentpost_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='reply',
            field=models.ManyToManyField(blank=True, to='posts.commentpost'),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('reply', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.commentpost')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_reply_liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
