# Generated by Django 4.0.6 on 2023-03-25 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='action_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poll',
            name='action_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
