# Generated by Django 4.1 on 2023-03-13 22:49

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username_email", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(editable=False, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_day",
                    models.DateField(blank=True, null=True, verbose_name="Birth Day"),
                ),
                (
                    "show_birth_day",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "Followers"),
                            ("onlyme", "Onlyme"),
                        ],
                        default="everyone",
                        max_length=9,
                    ),
                ),
                (
                    "show_full_name",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "Followers"),
                            ("onlyme", "Onlyme"),
                        ],
                        default="everyone",
                        max_length=9,
                    ),
                ),
                (
                    "show_gender",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "Followers"),
                            ("onlyme", "Onlyme"),
                        ],
                        default="everyone",
                        max_length=9,
                    ),
                ),
                (
                    "show_favorites",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "Followers"),
                            ("onlyme", "Onlyme"),
                        ],
                        default="everyone",
                        max_length=9,
                    ),
                ),
                (
                    "show_photo_profile",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("followers", "Followers"),
                            ("onlyme", "Onlyme"),
                        ],
                        default="everyone",
                        max_length=9,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=6,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "Dark"), ("light", "Light")],
                        default="light",
                        max_length=5,
                    ),
                ),
                ("show_photo_logout", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default/default_photo.jpg",
                        null=True,
                        upload_to=accounts.models.img_profile,
                        verbose_name="picture",
                    ),
                ),
                (
                    "photo_icon",
                    models.ImageField(
                        blank=True,
                        default="default/default_icon.png",
                        null=True,
                        upload_to=accounts.models.img_profile,
                        verbose_name="profil picture icon",
                    ),
                ),
                ("first_ip", models.GenericIPAddressField(editable=False, null=True)),
                ("ip", models.GenericIPAddressField(editable=False, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FollowRelationShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ftype",
                    models.CharField(
                        choices=[
                            ("user_user", "User User"),
                            ("user_page", "User Page"),
                            ("page_page", "Page Page"),
                        ],
                        max_length=9,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "following")},
            },
        ),
    ]
