# Generated by Django 4.1 on 2023-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesettings",
            name="show_pages_owned",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("followers", "Followers"),
                    ("onlyme", "Onlyme"),
                ],
                default="everyone",
                max_length=9,
            ),
        ),
    ]
