# Generated by Django 4.1 on 2023-05-24 01:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_conformaccount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/default_photo.png",
                null=True,
                upload_to=accounts.models.img_profile,
                verbose_name="picture",
            ),
        ),
    ]
