# Generated by Django 4.1 on 2022-09-07 22:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_photo_alter_profile_photo_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/default_photo.jpg",
                null=True,
                upload_to=accounts.models.img_profile,
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_icon",
            field=models.ImageField(
                blank=True,
                default="default/default_icon.png",
                null=True,
                upload_to=accounts.models.img_profile_icon,
                verbose_name="profil picture icon",
            ),
        ),
    ]
