# Generated by Django 4.1 on 2023-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="code",
            field=models.CharField(editable=False, max_length=7),
        ),
    ]
