# Generated by Django 4.1 on 2022-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_image_allow_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentimage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
