# Generated by Django 4.0.6 on 2023-03-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commentpost_reply_commentreply'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.commentreply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('liked', 'Liked'), ('commented', 'Commented'), ('comment_liked', 'Comment Liked'), ('replied', 'Replied'), ('reply_liked', 'Reply Liked'), ('followed', 'Followed'), ('event', 'Event')], max_length=13),
        ),
    ]
