# Generated by Django 4.1 on 2022-08-30 23:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_alter_notification_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("user", "followed"), ("user", "action")},
        ),
    ]
