# Generated by Django 4.0.6 on 2023-03-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commentpost_reply_commentreply'),
        ('notifications', '0002_notification_comment_alter_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.commentpost'),
        ),
    ]
