# Generated by Django 4.1 on 2022-08-30 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0005_commentimage_deleted"),
        ("posts", "0002_post_allow_comments"),
        ("notifications", "0003_alter_notification_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={
                ("user", "action", "post"),
                ("user", "action", "image"),
                ("user", "followed"),
            },
        ),
    ]
