# Generated by Django 4.1 on 2022-08-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action",
            field=models.CharField(
                choices=[
                    ("liked", "Liked"),
                    ("commented", "Commented"),
                    ("followed", "Followed"),
                ],
                max_length=13,
            ),
        ),
    ]
