# Generated by Django 4.1 on 2022-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action",
            field=models.CharField(
                choices=[
                    ("liked", "Liked"),
                    ("commented", "Commented"),
                    ("comment_liked", "Comment Liked"),
                    ("followed", "Followed"),
                ],
                max_length=13,
            ),
        ),
    ]
